### ISSUE TITLE
External yml files?

### ISSUE THREAD

**Issue by wilhelmer** [rosscdh/mkdocs-markdownextradata-plugin#4]
It would be nice if we could specify external file(s) where the extra variables are stored, similar to extra_css and extra_javascript:

#### mkdocs.yml
```yaml
extra_yml:
    - data.yml
```
#### data.yml

```yaml
customer:
    name: Your name here
    web: www.example.com
    salt: salt.example.com
```

Or is there already a way to parse external files?
