### ISSUE TITLE
Variables don't get resolved in Snippets

### ISSUE THREAD

**Issue by Stwissel** [rosscdh/mkdocs-markdownextradata-plugin#45]
I'm using your nice plugin together with the `pymdownx.snippets` plugin

## I have

```yaml
extra:
  test: 1.0.0
plugins:
  - search
  - awesome-pages
  - section-index
  - tags
  - markdownextradata: {}
```

and a `test.md`

```md
# Test of extras

This is top: {{test}}

--8<-- "snippet.md"

End
```

and a `snippet.md`

```md
In the snippet: {{test}}
```

## Expected outcome

```html
<h1>Test of extras</h1>

This is top: 1.0.0
In the snippet: 1.0.0

End
```

## Actual outcome

```html
<h1>Test of extras</h1>

This is top: 1.0.0
In the snippet: {{test}}

End
```

What do I miss?

**Comment by rosscdh** [comment]
Hey there thanks for your interest.

Off the top of my head try

- markdownextradata: {}

Becomes

- markdownextradata


Hope that helps. Been a while since ive worked on this app!

**Comment by Stwissel** [comment]
Tried that too. I suspect it might be the sequence of plugins. Mkdocs is particular about it. I'll experiment and report back

**Comment by Stwissel** [comment]
Played with various combinations of plugin and markdown extension sequences to no success.
I also renamed in one attempt the snippet directory to `.snippet` so it would be first in the directory list.

 Interesting observation: when I load `snippet.md` directly from the URL, it works as expected and variables are resolved. Looks to me like a lifecycle issue where the snippet plugin ignores the markdownextradata.

**Comment by rosscdh** [comment]
Thanks for the feedback.

Would you kind sending your yaml and I’ll try replicate and fix when I get
a second?

Best

**Comment by Stwissel** [comment]
Here you go:

```yaml
#Project Information
site_name: MKDocs Test
site_url: https://github.com/
site_description: >-
  A test
use_directory_urls: false
# Theme Configuration
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
  #custom_dir: theme_overrides/
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
  favicon: favicon.ico

  # Static files
  static_templates:
    - 404.html

# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      base_path:
        - "docs/snippets"

extra:
  test: 1.0.0
  
plugins:
  - markdownextradata
  - search
  - awesome-pages
  - section-index
  - tags

```
