### ISSUE TITLE
Macro in included page

### ISSUE THREAD

**Issue by xtran3** [rosscdh/mkdocs-markdownextradata-plugin#7]
Could someone help me on this issue?

I have project structure like this:
- Showcase
	Showcase.md
	+ Cases
		Case1.md
- images
	image1.PNG

	
_mkdocs.yml_ file:
```
...
extra:
  site:
    image_path: 'http://abc/images/'
plugins:
  - search
  - git-revision-date
  - macros
  - markdownextradata
...
```
	
_Showcase.md_ content:

`{!Showcase/Cases/Case1.md!}`

_Case1.md_ content:

`![SampleImage]({{ site.image_path }}image1.PNG)`

If I go to **http://abc/Showcase/Cases/Case1**, then I can see the image1.PNG. The real url is **http://abc/images/image1.PNG**.
But if I go to **http://abc/Showcase/Cases**, the image load failed. I check the HTML source:
`<img alt="SampleImage" src="{{ site.image_path }}image1.PNG">`
The **{{ site.image_path }}** is not generated!
It seems like the macro does not work when using "include" page in .md

Could you please help to verify this?
